//intercepts AST generated by remark-durectuve
import { visit } from 'unist-util-visit'; //traverse the AST

export function customDirectives() {
    return (tree) => {
        visit(tree, (node) => {
            if (
                node.type === 'textDirective' ||
                node.type === 'leafDirective' ||
                node.type === 'containerDirective'
            ) {
                const data = node.data || (node.data = {});

                if (node.type === 'containerDirective') {
                    const directiveName = node.name;

                    //NOTE 1: tell pipeline what HTML tag to generate 
                    data.hName = 'div';
                    //TailwindCSS / custom styles
                    data.hProperties = {
                        //TASK : // Add layout classes here
                        className: `custom-directive box-${directiveName}`,
                    };
                }

                if (node.type === 'textDirective' && node.name === 'span') {
                    //Attributes maps the content inside curly braces {color=red}
                    const attributes = node.attributes || {};

                    //map node to an inline HTML element with the specified color
                    data.hName = 'span';
                    data.hProperties = {
                        style: {
                            color: attributes.color || 'inherit'
                        },
                        className: 'custom-colored-span',
                    };
                }
            }
        });
    };
}