//intercepts AST generated by remark-directive
import { visit } from 'unist-util-visit'; //traverse the AST

export function customDirectives() {
    return (tree) => {
        visit(tree, (node) => {
            if (
                node.type === 'textDirective' ||
                node.type === 'leafDirective' ||
                node.type === 'containerDirective'
            ) {
                const data = node.data || (node.data = {});

                if (node.type === 'containerDirective') {
                    const directiveName = node.name;
                    data.hName = 'div';
                    data.hProperties = {
                        className: ['custom-directive', `box-${directiveName}`],
                    };
                }

                // For custom styling use inline HTML in markdown: <span style="color: red">text</span>
                // HTML spans are processed by rehypeRaw plugin with allowDangerousHtml: true
                if (node.type === 'textDirective' && node.name === 'span') {
                    //Attributes maps the content inside curly braces {color=red}
                    const attributes = node.attributes || {};
                    let color = 'inherit';
                    
                    // Try to extract color from various possible attribute formats
                    if (attributes.color) {
                        color = attributes.color;
                    } else if (typeof attributes === 'string' && attributes.includes('color=')) {
                        const match = attributes.match(/color=(['"]?)([^'"\s}]+)\1/);
                        if (match) {
                            color = match[2];
                        }
                    }

                    //map node to an inline HTML element with the specified color
                    data.hName = 'span';
                    data.hProperties = {
                        style: `color: ${color}`,
                        className: 'custom-colored-span',
                    };
                }
            }
        });
    };
}